### ISSUE TITLE
how to build the dataset

### ISSUE THREAD

**Issue by ooochen-30** [tvaranka/fineface#4]
@tvaranka  
i want to build my own dataset, but i have no idea how do u operate on your dataset after filtering. As you mentioned in your paper that "To ensure T2I model compatibility, images from AffectNet and DISFA are captioned with BLIP-2 [22]..."  how do you design your prompt for blip-2? What level of description is needed for the facial expression?

**Comment by tvaranka** [comment]
Thanks for pointing out this detail, I will update it to the paper. For the image captioning no prompt is used. BLIP-2 will use the beginning token to start generation. There is no need to extract facial expression information from the prompt, in fact, we kind of want the opposite as the facial expression control should be coming from AUs. The prompt is there to mostly describe the scene, the person and ensure compatibility. For AU extraction LibreFace is used.

I apologize for the delay, but I will be uploading the dataset later.

**Comment by ooochen-30** [comment]
> Thanks for pointing out this detail, I will update it to the paper. For the image captioning no prompt is used. BLIP-2 will use the beginning token to start generation. There is no need to extract facial expression information from the prompt, in fact, we kind of want the opposite as the facial expression control should be coming from AUs. The prompt is there to mostly describe the scene, the person and ensure compatibility. For AU extraction LibreFace is used.
> 
> I apologize for the delay, but I will be uploading the dataset later.

Thanks for your answer, i think i may get your idea and have a try.

**Comment by tvaranka** [comment]
Data loading script is uploaded #9 and the metadata can be found from https://huggingface.co/Tvaranka/fineface/tree/main.
